basePath: /
definitions:
  dto.UserCreatedDTO:
    properties:
      token:
        type: string
    type: object
  models.User:
    properties:
      birthday:
        type: string
      expectedSalary:
        type: number
      id:
        type: string
      login:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
host: http://localhost:8080
info:
  contact:
    email: nahuy@kaniv.com
    name: Backend developer
    url: https://t.me/bringmetheaugust
  description: Work hard, play hard
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fudol OpenAPI doc
  version: 0.0.1
paths:
  /sigup:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserCreatedDTO'
        "400":
          description: invalid body fields.
          schema: {}
        "406":
          description: nickname or login is existed.
          schema: {}
      summary: sign up
      tags:
      - Auth
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: Bearer
              type: string
          schema:
            $ref: '#/definitions/models.User'
      security:
      - ApiKeyAuth: []
      summary: get user data
      tags:
      - User
securityDefinitions:
  Bearer:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
