services:
  admin:
    container_name: fudol_web_client
    restart: unless-stopped
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./web_client:/app
    depends_on:
      - api
    environment:
      - API_HOST

  api:
    container_name: fudol_api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - GO_VERSION
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - TOKEN_KEY
      - IS_CONTAINER=true
    ports:
      - 8080:80
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    container_name: fudol_db
    restart: unless-stopped
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - ./db/data:/data/db
